apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-conf-first-db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-log-second-db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-third-db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql
