---
apiVersion: v1
kind: Secret
metadata:
  name: tngr-db-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2xpbmlxdWU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tngr-db-mysql8
  labels:
    aim: support
    env: build
    service: mysql
spec:
  selector:
    matchLabels:
      service: tngr-mysql-database
  template:
    metadata:
      labels:
        service: tngr-mysql-database
    spec:
      containers:
        - name: tngr-db
          image: mysql:8.0.27
          volumeMounts:
            - mountPath: /var/log/mysql
              name: mysql-log-second-db-volume
            - mountPath: /var/lib/mysql
              name: mysql-data-third-db-volume
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: clinique
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tngr-db-secret
                  key: ROOT_PASSWORD
      volumes:
        - name: mysql-log-second-db-volume
          persistentVolumeClaim:
            claimName: second-claim
        - name: mysql-data-third-db-volume
          persistentVolumeClaim:
            claimName: third-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tngr-database-svc
spec:
  type: NodePort
  selector:
    service: tngr-mysql-database
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
