---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsb2NhbGhvc3Q6NTAwMCI6eyJ1c2VybmFtZSI6Im1ibGNvbnRhaW5lcml6ZSIsInBhc3N3b3JkIjoiMTIzIiwiZW1haWwiOiJtb2hhbW1lZC5ibGFsQGdtYWlsLmNvbSIsImF1dGgiOiJiV0pzWTI5dWRHRnBibVZ5YVhwbE9qRXlNdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ${NORMALIZED_APP_NAME}
  name: ${NORMALIZED_APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NORMALIZED_APP_NAME}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${NORMALIZED_APP_NAME}
    spec:
      containers:
      - image: ${DOCKER_REPO_URL}/${DOCKER_IMAGE_NORMALIZED_NAME}
        name: ${DOCKER_IMAGE_NORMALIZED_NAME}
        resources: {}
        env:
        - name: NODE_ENV
          value: ${TARGET_ENV}
      imagePullSecrets:
      - name: myregistrykey
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ${NORMALIZED_APP_NAME}
  name: ${NORMALIZED_APP_NAME}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${NORMALIZED_APP_NAME}
  type: NodePort
status:
  loadBalancer: {}
