apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-app
    spec:
      containers:
      - image: localhost:5000/my-app-im
        name: my-app-im-w8fvd
        resources: {}
      imagePullSecrets:
      - name: myregistrykey
status: {}
